Alter testfile
TomAdam/protected-branches-test pull request #1
Opened 2017-05-04 23:27 UTC by TomAdam

2017-05-04 23:34 UTC, TomAdam commented on testfile
> +Test
This will never work like this!

2017-05-04 23:36 UTC, tborealis reviewed
Better now

2017-05-05 10:47 UTC, DaveLiddament requested changes

2017-05-05 10:47 UTC, DaveLiddament commented on testfile
> -Test
This is wrong

2017-05-05 10:47 UTC, DaveLiddament commented on failing-test
> +exit(0);
I'd make this 1

2017-05-05 10:47 UTC, DaveLiddament commented on testfile
> +Test
ANother review

2017-05-05 10:52 UTC, TomAdam commented on failing-test
> +exit(0);
1 makes this fail

2017-05-05 10:54 UTC, DaveLiddament submitted a review, later dismissed

2017-05-05 11:01 UTC, DaveLiddament approved these changes

2017-05-05 11:03 UTC, merged